### ISSUE TITLE
help：training result

### ISSUE THREAD

**Issue by buziran** [Jaulaucoeng/HOS-Net#3]
感谢你们提出的HOS-NET网络，在提供新的模型的基础上，提升了的网络模型的性能。

问题1：在sysu数据集上复现论文的结果如下：
运行train_hos_net，程序默认设置
1。训练结果
Test Epoch: 99
Extracting Gallery Feature...
Extracting Time:	 0.339
Extracting Query Feature...
Extracting Time:	 2.808
Evaluation Time:	 1.501
POOL:   Rank-1: 71.44% | Rank-5: 92.16% | Rank-10: 96.71%| Rank-20: 98.97%| mAP: 68.36%| mINP: 54.89%
FC:   Rank-1: 72.29% | Rank-5: 92.35% | Rank-10: 96.84%| Rank-20: 99.24%| mAP: 69.33%| mINP: 56.35%
Best Epoch [92]

其中best epoch92的结果如图
Test Epoch: 92
Extracting Gallery Feature...
Extracting Time:	 0.355
Extracting Query Feature...
Extracting Time:	 2.822
Evaluation Time:	 1.477
POOL:   Rank-1: 71.55% | Rank-5: 92.16% | Rank-10: 96.58%| Rank-20: 99.00%| mAP: 68.52%| mINP: 54.81%
FC:   Rank-1: 72.68% | Rank-5: 92.64% | Rank-10: 97.00%| Rank-20: 99.16%| mAP: 69.52%| mINP: 56.23%
Best Epoch [92]

2。测试结果
。。。。
Test Trial: 8
FC:   Rank-1: 73.02% | Rank-5: 93.37% | Rank-10: 97.90%| Rank-20: 99.53%| mAP: 71.22%| mINP: 59.08%
POOL: Rank-1: 72.65% | Rank-5: 92.82% | Rank-10: 97.66%| Rank-20: 99.58%| mAP: 70.64%| mINP: 58.38%
Extracting Gallery Feature...
Extracting Time:	 1.061
Test Trial: 9
FC:   Rank-1: 74.23% | Rank-5: 93.74% | Rank-10: 98.19%| Rank-20: 99.76%| mAP: 71.49%| mINP: 59.82%
POOL: Rank-1: 74.13% | Rank-5: 93.45% | Rank-10: 98.05%| Rank-20: 99.82%| mAP: 71.04%| mINP: 59.11%
All Average:
FC:     Rank-1: 74.78% | Rank-5: 93.83% | Rank-10: 97.79%| Rank-20: 99.58%| mAP: 72.56%| mINP: 60.89%
POOL:   Rank-1: 74.38% | Rank-5: 93.52% | Rank-10: 97.66%| Rank-20: 99.58%| mAP: 71.97%| mINP: 60.01%

发现并没有达到论文的训练效果 75.6/74.2，请问是有我其他的测试策略有问题吗？

问题2：论文中数据集处理过程，用的256x128的处理，程序中用的288×144，是我理解的有误吗？

期待得到您的回复和指导，谢谢

**Comment by Jaulaucoeng** [comment]
问题1：74.8和论文结果75.6相差0.8，可能受到不同硬件环境的影响，您可以尝试不同的batch-size，lr等等超参数。

问题2: 以288×144为准，您也可以尝试更大的图像大小，可参考DEEN。

**Comment by buziran** [comment]
非常感谢您的回复。请问您发布的结果是由您发布的程序默认参数训练的结果吗？

**Comment by Jaulaucoeng** [comment]
发布的代码我经过重新整理，在发布之前我重新跑过，应该是没问题的。
