### ISSUE TITLE
测试结果

### ISSUE THREAD

**Issue by eatgreenjiao** [Jaulaucoeng/HOS-Net#4]
你好，我在regdb数据集上训练，将test_mode = [2, 1]切换成了test_mode = [1, 2]，也就是修改了IR-VIS，但是mAP的结果只有0.67左右，在test_mode = [2, 1]训练并进行测试，结果跟论文所提供的结果相近，请您能否为我解释一下，从IR-VIS的训练是否只需修改test_mode参数

**Comment by Jaulaucoeng** [comment]
Q1：我在regdb数据集上训练，将test_mode = [2, 1]切换成了test_mode = [1, 2]，也就是修改了IR-VIS，但是mAP的结果只有0.67左右。
A1：测试的时候应该是用tvsearch参数吧，但是mAP的结果只有0.67左右，这个情况我没有遇到过，推测是不是没有加载权重。
Q2：从IR-VIS的训练是否只需修改test_mode参数。
A2：我在训练的时候只训练了V-to-I，然后测试的时候是V-to-I和I-to-V。

**Comment by eatgreenjiao** [comment]
您好作者，关于sysu-mm01的map指标，我按照您的源代码跑了两次，但结果总是差了有好几个点，在train_sle中的权重加载了你提供的文件，其他两个训练文件分别加载上一步的权重，请问是不是有地方需要修改
